import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { Toaster } from "sonner";
import {AuthProvider} from '@/context/AuthContext'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Toaster
            position="top-center"
            toastOptions={{
              classNames: {
                success: "bg-green-400 text-white",
                error: "bg-red-500 text-white",
              },
            }}
          />
          <Header />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
